### ISSUE TITLE
Task 3.3: implement of hessian matrix

### ISSUE THREAD

**Issue by FenglongSong** [cmm-21/a1#5]
Hi all, I'm confused about the computation of Hessian matrix, specifically how to compute dJ/dtheta * v. Since dJ/dtheta is a tensor, what should be the product of a tensor and a vector? In my opinion, I believe it should be the linear combination of matrices in the tensor. But my code cannot pass test 6. So I'm asking this question to find the possible reasons for my failure. 

Thank you very much!

**Comment by liyuesolo** [comment]
Hi, a 3rd order tensor times a vector gives you a matrix just as a matrix(2nd tensor) times a vector gives you a vector.

**Comment by FenglongSong** [comment]
> Hi, a 3rd order tensor times a vector gives you a matrix just as a matrix(2nd tensor) times a vector gives you a vector.

Thank you, I could see the result is a matrix and what makes me confuse is the rule of multiplication of a tensor and a vector. 
Anyway, I found the following rule works although I don't know exactly why: let dJ_dtheta be a 2x2x2 tensor as defined in ForwardKinematics.h, then dJ_dtheta * v = [dJ_dtheta[0]^T * v, dJ_dtheta[1]^T * v]

**Comment by Zzyus** [comment]
I guess this is due to the way that the hessian tensor is arranged. It seems like if we want to pass test 3, the tensor must be arranged in a form like [x_i, f, x_j] because the ground truth matrices they provide are calculated this way. When you do $$dJ_dx * v$$, you need to compute dot products in the "f" dimension, which means to first call dJ_dtheat[x_i] to get [f, x_j], transpose to get [x_j, f], compute the dot products to get [x_j], and finally put all x_i back together to get[x_i, x_j].

**Comment by moritzge** [comment]
Tensors can easily get confusing. My advice is to first think about each entry of the Hessian individually and to write down the analytical solution for each entry in the Hessian by hand on paper. You should now be able to see, how to use the Tensor computed in ddendEffector_ddangles. And where transposes might be necessary.
I hope this helps!
